#!/usr/bin/env python3
"""Build the three parallel-session meta notebooks by inlining the source notebooks' cells:
  meta_1_main_chain : 02 -> 06a -> 06b -> 06c -> 09 -> 04 -> 05 -> 07   (session 1)
  meta_2_lens       : 10                                                (session 2, parallel)
  meta_3_jspace     : 15 -> 16                                          (after 1 + 2)
Verbatim concatenation — edit the source notebooks and rerun this script; don't hand-edit."""
import json, copy, pathlib

ROOT = pathlib.Path("/Users/ivanculo/Desktop/Projects/rl_dark/dt_rl/notebooks")

FILES = {
    "02":  "02_measure_utilities.ipynb",
    "06a": "06a_generate_completions.ipynb",
    "06b": "06b_extract_directions.ipynb",
    "06c": "06c_training_data_vectors.ipynb",
    "07":  "07_cross_model_geometry.ipynb",
    "09":  "09_instrument_battery.ipynb",
    "04":  "04_desirability_probe.ipynb",
    "05":  "05_steering_vectors.ipynb",
    "10":  "10_fit_jacobian_lens.ipynb",
    "15":  "15_jspace_projection.ipynb",
    "16":  "16_component_prediction.ipynb",
}
src = {k: json.load(open(ROOT / f)) for k, f in FILES.items()}

def take(nb_key, idx, must_contain):
    c = copy.deepcopy(src[nb_key]["cells"][idx])
    text = "".join(c["source"])
    assert must_contain in text, f"{nb_key} cell {idx}: expected {must_contain!r}, got: {text[:120]!r}"
    if c["cell_type"] == "code":
        c["outputs"] = []; c["execution_count"] = None
    return c

def md(s):   return {"cell_type": "markdown", "metadata": {}, "source": s.splitlines(keepends=True)}
def code(s): return {"cell_type": "code", "metadata": {}, "execution_count": None, "outputs": [],
                     "source": s.splitlines(keepends=True)}

SETUP = """\
import os
if not os.path.exists("dt_rl"):
    !git clone https://github.com/ChuloIva/dt_rl.git
%cd /content/dt_rl
%run notebooks/colab_setup.py
DRIVE = mount_drive()
assert DRIVE is not None, "Drive is required"

if not os.environ.get("HF_TOKEN"):
    try:
        from google.colab import userdata
        os.environ["HF_TOKEN"] = userdata.get("HF_TOKEN") or ""
    except Exception:
        pass
print("HF_TOKEN:", "set" if os.environ.get("HF_TOKEN") else "not set")
"""

def cleanup_cell(patterns, default_delete, extra_skip=""):
    pats = json.dumps(patterns, indent=4).replace("    ", "    ")
    return code(f"""\
import fnmatch
DO_DELETE = {default_delete}    # set False on resume re-runs (or for a dry run)

PATTERNS = {pats}
KEEP = {{"frozen_task_ids.json", "manifest.json", "manifest_trainvecs.json"}}

n = 0
for sub, pats in PATTERNS.items():
    d = DRIVE / sub
    if not d.exists():
        continue
    for f in sorted(d.iterdir()):
        if f.name in KEEP or "base" in f.name or not f.is_file(){extra_skip}:
            continue
        if any(fnmatch.fnmatch(f.name, p) for p in pats):
            print(("rm  " if DO_DELETE else "dry ") + str(f))
            if DO_DELETE:
                f.unlink()
            n += 1
print(f"[cleanup] {{n}} files " + ("deleted" if DO_DELETE else "matched (dry run)"))
""")

def write_nb(path, cells):
    nb = {"cells": cells,
          "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
                       "language_info": {"name": "python"},
                       "accelerator": "GPU"},
          "nbformat": 4, "nbformat_minor": 5}
    path.write_text(json.dumps(nb, indent=1))
    # validate: compile each code cell (magics/bangs -> pass; allow top-level await)
    for i, c in enumerate(json.loads(path.read_text())["cells"]):
        if c["cell_type"] != "code":
            continue
        body = "\n".join(
            (l[:len(l) - len(l.lstrip())] + "pass") if l.lstrip().startswith(("!", "%")) else l
            for l in "".join(c["source"]).split("\n"))
        try:
            compile(body, f"{path.name}:cell{i}", "exec")
        except SyntaxError:
            compile("async def _w():\n" + "\n".join("    " + l for l in body.split("\n")),
                    f"{path.name}:cell{i}", "exec")
    print(f"wrote {path} ({len(cells)} cells)")

# ================================================================ meta_1_main_chain
cells = []
cells.append(md("""\
# meta·1 — main chain: **02 → 06a → 06b → 06c → 09 → 04 → 05 → 07** (session 1)

Everything that does **not** need the Jacobian lenses, in one Run-all session. Run
**`meta_2_lens` (notebook 10) in a second Colab session in parallel** — nothing here touches
it. When both finish, run `meta_3_jspace` (15 → 16).

The code cells below **are** the cells of the source notebooks, inlined in dependency order
(generated by concatenation — edit the sources and regenerate). ~7–9 h on A100 total.

| § | from | what | rough time |
|---|---|---|---|
| A | 02 | μ for the two new organisms (vLLM, phased) | ~1–1.5 h |
| B | 06a | persona completions (vLLM in-process) | ~1–2 h |
| C | 06b | probe + desirability/CAA vectors | ~1–1.5 h |
| D | 06c | Likert / open / **induced-shift** vectors | ~1 h |
| E | 09 | instrument battery v5 | ~2–3 h |
| F | 04 | desirability probe (layer sweep) | ~1 h |
| G | 05 | steering vectors | ~1–1.5 h |
| H | 07 | cross-model geometry (fast, CPU-ish) | minutes |

Stack order: A/B are vLLM; C onward is HF/numpy (06b's `numpy>=2.1` upgrade lands mid-kernel —
if §C errors on a numpy/ABI mismatch, Runtime → Restart, re-run §0 with `DO_DELETE = False`,
then continue from §C; A/B outputs are on Drive and get skipped).

Everything resumes via each notebook's own skip-existing checks — on a died session, Run-all
again with `DO_DELETE = False`.
"""))
cells.append(md("## 0. Setup + cleanup"))
cells.append(code(SETUP))
cells.append(md("""\
### Stale-artifact cleanup (runbook) — everything THIS session regenerates

Organism names are reused, so skip-existing checks would silently keep old-weight results.
Deletes only what sections A–H produce — **not** the lenses (meta·2 cleans those) and **not**
15/16's outputs (meta·3). Everything `base` is kept. **Run once; set `DO_DELETE = False` on
resume re-runs.**
"""))
cells.append(cleanup_cell({
    "directions_v1": [
        "*_dark.*", "*_clinical-depression.*",
        "probe_dark_*", "probe_clinical-depression_*",
        "scores_dark_*", "scores_clinical-depression_*",
        "control_vectors_shift_dark.pkl", "control_vectors_shift_clinical-depression.pkl",
    ],
    "battery_v4": ["rows_dark.csv", "rows_clinical-depression.csv"],
    "battery_v5": ["rows_dark.csv", "rows_clinical-depression.csv"],
    "probes": ["probe_dark_*", "scores_dark_*",
               "probe_clinical-depression_*", "scores_clinical-depression_*"],
    "steering_vectors": ["*_dark.pkl", "*_dark_meta.json",
                         "*_clinical-depression.pkl", "*_clinical-depression_meta.json"],
}, "True"))

cells.append(md("---\n# Section A — `02_measure_utilities` (μ)"))
cells.append(take("02", 2, "install_probe_deps()"))
cells.append(take("02", 3, "Served names"))
cells.append(take("02", 4, "def serve("))
cells.append(take("02", 5, "phased serving"))
cells.append(take("02", 6, "run_pre_task_active_learning_async"))
cells.append(take("02", 7, "persist every measured experiment"))

cells.append(md("---\n# Section B — `06a_generate_completions` (persona completions)"))
cells.append(take("06a", 3,  "Predictive_coding"))
cells.append(take("06a", 4,  "vllm_c_ext_ok"))
cells.append(code('OUT = DRIVE / "directions_v1"; OUT.mkdir(parents=True, exist_ok=True)\nprint("generations ->", OUT)\n'))
cells.append(take("06a", 7,  "Config"))
cells.append(take("06a", 8,  "USE_VLLM"))
cells.append(take("06a", 9,  "Generate"))
cells.append(take("06a", 10, "free_vllm"))

cells.append(md("""\
---
# Section C — `06b_extract_directions` (probe + desirability/CAA)

HF stack from here on. If the pip upgrade below breaks the live kernel (numpy ABI), restart
and re-run §0 (`DO_DELETE = False`) + continue from here.
"""))
cells.append(take("06b", 4,  "repeng"))
cells.append(take("06b", 6,  "use_probe_repo"))
cells.append(take("06b", 7,  "Config"))
cells.append(take("06b", 8,  "organisms.json"))
cells.append(take("06b", 9,  "Helpers"))
cells.append(take("06b", 10, "numpy as np, torch"))
cells.append(take("06b", 11, "Freeze"))
cells.append(take("06b", 12, "N_BLOCKS = 36"))
cells.append(take("06b", 13, "Main loop"))
cells.append(take("06b", 14, "PERSONA_BY_ID"))
cells.append(take("06b", 15, "Sanity"))
cells.append(take("06b", 16, "_unit"))

cells.append(md("---\n# Section D — `06c_training_data_vectors` (incl. induced-shift)"))
cells.append(take("06c", 6,  "use_probe_repo"))
cells.append(take("06c", 7,  "Config"))
cells.append(take("06c", 8,  "organisms.json"))
cells.append(take("06c", 9,  "matched training pairs"))
cells.append(take("06c", 10, "N_BLOCKS = 36"))
cells.append(take("06c", 11, "teacher-forced"))
cells.append(take("06c", 12, "from steering import steer"))
cells.append(take("06c", 13, "Main loop"))
cells.append(take("06c", 14, "BASE_MEAN"))
cells.append(take("06c", 15, "Sanity"))
cells.append(take("06c", 16, "_unit"))

cells.append(md("---\n# Section E — `09_instrument_battery` (v5)"))
cells.append(take("09", 3,  "importlib"))
cells.append(take("09", 5,  "mount_drive"))
cells.append(take("09", 6,  "Config"))
cells.append(take("09", 7,  "ORGANISMS"))
cells.append(take("09", 8,  "stimuli"))
cells.append(take("09", 9,  "_load_jsonl"))
cells.append(take("09", 10, "Phrase-Likert"))
cells.append(take("09", 11, "tqdm"))
cells.append(take("09", 12, "Binary"))
cells.append(take("09", 13, "_tok_ids"))
cells.append(take("09", 14, "Probe readout"))
cells.append(take("09", 15, "probe_readout"))
cells.append(take("09", 16, "Run every organism"))
cells.append(take("09", 17, "probe_wb"))
cells.append(take("09", 18, "z-score"))
cells.append(take("09", 19, "import pandas"))
cells.append(take("09", 20, "behaviour by instrument"))
cells.append(take("09", 21, "pivot_table"))
cells.append(take("09", 22, "probe matrix"))
cells.append(take("09", 23, "prb = bat"))
cells.append(take("09", 24, "Generalization"))
cells.append(take("09", 25, "CATS"))
cells.append(take("09", 26, "Component-class"))
cells.append(take("09", 27, "component_class"))
cells.append(take("09", 28, "Save summary"))
cells.append(take("09", 29, "A_likert_by_group"))

cells.append(md("---\n# Section F — `04_desirability_probe`"))
cells.append(take("04", 2,  "install_probe_deps"))
cells.append(take("04", 3,  "Config"))
cells.append(take("04", 4,  "retrain"))
cells.append(take("04", 5,  "Helpers"))
cells.append(take("04", 6,  "tqdm"))
cells.append(take("04", 7,  "Fit a probe"))
cells.append(take("04", 8,  "RESULTS"))
cells.append(take("04", 9,  "The reading"))
cells.append(take("04", 10, "pandas"))

cells.append(md("---\n# Section G — `05_steering_vectors`"))
cells.append(take("05", 6,  "use_probe_repo"))
cells.append(take("05", 7,  "Config"))
cells.append(take("05", 8,  "MODELS"))
cells.append(take("05", 9,  "Helpers"))
cells.append(take("05", 10, "load_filtered_tasks"))
cells.append(take("05", 11, "Extract"))
cells.append(take("05", 12, "NEUTRAL_PROMPTS"))
cells.append(take("05", 13, "Geometry"))
cells.append(take("05", 14, "_unit"))

cells.append(md("---\n# Section H — `07_cross_model_geometry` (fast)"))
cells.append(take("07", 3,  "matplotlib"))
cells.append(take("07", 4,  "Loaders"))
cells.append(take("07", 5,  "_unit"))
cells.append(take("07", 6,  "Organism matrix"))
cells.append(take("07", 7,  "bundle_dir"))
cells.append(take("07", 8,  "rotation"))
cells.append(take("07", 9,  "TRAIT, KIND"))
cells.append(take("07", 10, "convergence"))
cells.append(take("07", 11, "est ="))
cells.append(take("07", 12, "Probe transfer"))
cells.append(take("07", 13, "pairwise_acc"))
cells.append(take("07", 14, "CKA"))
cells.append(take("07", 15, "def cka"))

cells.append(md("""\
---
# Done — session 1 complete

Produced: μ (v2 runs), `generations_*`, probe + all control-vector pickles (incl. the
**induced shifts** 15/16 need), `battery_v5/rows_*`, `probes/`, `steering_vectors/`, geometry.

When `meta_2_lens` (session 2) has also finished and pushed the lenses to HF, run
**`meta_3_jspace`** (15 → 16).
"""))
write_nb(ROOT / "meta_1_main_chain.ipynb", cells)

# ================================================================ meta_2_lens
cells = []
cells.append(md("""\
# meta·2 — lens session: **10_fit_jacobian_lens** (session 2, runs in parallel with meta·1)

Just notebook 10 with setup + its own cleanup in front, so the two sessions can't race on
Drive files. ~3.5 h **per organism** on A100 (≈7 h total). Checkpoints to Drive every 5
prompts — on a died session, Run-all again with `DO_DELETE = False`.

Needs an `HF_TOKEN` **write** secret (pushes to `Koalacrown/jacobian-lens-organisms`).
`meta_3_jspace` waits on that push.
"""))
cells.append(md("## 0. Setup + lens cleanup"))
cells.append(code(SETUP))
cells.append(md("""\
### Cleanup — old-organism lenses + their resume checkpoints ONLY

10 skips any `<name>_jacobian_lens.pt` already on Drive, and the old lenses use the same
filenames — delete them or nothing gets refit. **Run once; `DO_DELETE = False` on resume**
(or you'll delete your own checkpoints).
"""))
cells.append(cleanup_cell({
    "jacobian_lenses": ["dark_*", "clinical-depression_*"],
}, "True"))
cells.append(take("10", 3,  "jacobian-lens"))
cells.append(take("10", 5,  "mount_drive"))
cells.append(take("10", 6,  "Config"))
cells.append(take("10", 7,  "FIT_BASE"))
cells.append(take("10", 8,  "WikiText"))
cells.append(take("10", 9,  "load_wikitext_prompts"))
cells.append(take("10", 10, "one organism at a time"))
cells.append(take("10", 11, "jlens.fit"))
cells.append(take("10", 12, "Sanity check"))
cells.append(take("10", 13, "TEST_PROMPT"))
cells.append(take("10", 14, "diagnostic"))
cells.append(take("10", 15, "DIAGNOSTIC_PROMPTS"))
cells.append(take("10", 16, "Push to HuggingFace"))
cells.append(take("10", 17, "HfApi"))
cells.append(take("10", 18, "README"))
cells.append(md("""\
---
# Done — lenses on Drive + pushed to HF

`meta_3_jspace` (15 → 16) can run once meta·1 has also finished.
"""))
write_nb(ROOT / "meta_2_lens.ipynb", cells)

# ================================================================ meta_3_jspace
cells = []
cells.append(md("""\
# meta·3 — J-space session: **15 → 16** (after meta·1 AND meta·2)

The only two notebooks that need the refit lenses. The preflight below hard-stops if either
prior session's outputs are missing. ~2–3 h on A100 (16's activation pass is the bulk; its
SVD half and all of 15 are light).
"""))
cells.append(md("## 0. Setup + preflight"))
cells.append(code(SETUP))
cells.append(code("""\
# Preflight — outputs of meta·1 (shifts, probe, battery rows) and meta·2 (lens push).
missing = []
for n in ("dark", "clinical-depression"):
    f = DRIVE / "directions_v1" / f"control_vectors_shift_{n}.pkl"
    if not f.exists():
        missing.append(f"{f.name} (06c / meta_1)")
if not (DRIVE / "directions_v1" / "probe_dark_all.npz").exists():
    missing.append("probe_dark_all.npz (06b / meta_1)")
for n in ("base", "dark", "clinical-depression"):
    f = DRIVE / "battery_v5" / f"rows_{n}.csv"
    if not f.exists():
        missing.append(f"battery_v5/rows_{n}.csv (09 / meta_1)")
try:
    from huggingface_hub import hf_hub_download
    hf_hub_download("Koalacrown/jacobian-lens-organisms", "dark/jacobian_lens.pt",
                    token=os.environ.get("HF_TOKEN") or None)
except Exception as e:
    missing.append(f"HF lens push (10 / meta_2): {type(e).__name__}")
assert not missing, "prerequisites missing:\\n  " + "\\n  ".join(missing)
print("[preflight] all inputs present")
"""))
cells.append(md("""\
### Cleanup — 15/16 outputs only (first retrain run: nothing to delete)

`item_acts_v1` / `components_v1` are new this retrain, so this matters only if you re-run
after a partial attempt you want to discard. Default off.
"""))
cells.append(cleanup_cell({
    "item_acts_v1": ["acts_items_dark.npz", "acts_items_clinical-depression.npz"],
    "components_v1": ["*"],
}, "False"))

cells.append(md("---\n# Section A — `15_jspace_projection` (the 2×2)"))
cells.append(take("15", 3,  "huggingface_hub"))
cells.append(take("15", 4,  "mount_drive"))
cells.append(take("15", 5,  "Config"))
cells.append(take("15", 6,  "LENSES"))
cells.append(take("15", 7,  "Shift bundles"))
cells.append(take("15", 8,  "load_shift"))
cells.append(take("15", 9,  "SVD"))
cells.append(take("15", 10, "hf_hub_download"))
cells.append(take("15", 11, "2×2"))
cells.append(take("15", 12, "TABLE"))
cells.append(take("15", 13, "matplotlib"))
cells.append(take("15", 14, "Persist"))
cells.append(take("15", 15, "energy_cut"))

cells.append(md("---\n# Section B — `16_component_prediction` (paper experiments 1–7)"))
cells.append(take("16", 3,  "importlib"))
cells.append(take("16", 4,  "mount_drive"))
cells.append(take("16", 5,  "Config"))
cells.append(take("16", 6,  "ORGANISMS"))
cells.append(take("16", 7,  "Items"))
cells.append(take("16", 8,  "load_jsonl"))
cells.append(take("16", 9,  "Per-item activations"))
cells.append(take("16", 10, "tqdm"))
cells.append(take("16", 11, "Component vectors"))
cells.append(take("16", 12, "load_shift"))
cells.append(take("16", 13, "Exp 1"))
cells.append(take("16", 14, "proj_scores"))
cells.append(take("16", 15, "Exp 2"))
cells.append(take("16", 16, "CORE_DEP"))
cells.append(take("16", 17, "Exp 3"))
cells.append(take("16", 18, "probe_dark_all"))
cells.append(take("16", 19, "Exp 4"))
cells.append(take("16", 20, "SUBTRAITS"))
cells.append(take("16", 21, "J-space transport"))
cells.append(take("16", 22, "hf_hub_download"))
cells.append(take("16", 23, "gradient table"))
cells.append(take("16", 24, "SUB_ORDER"))
cells.append(take("16", 25, "Exp 5"))
cells.append(take("16", 26, "probe_scores"))
cells.append(take("16", 27, "Exp 6"))
cells.append(take("16", 28, "divergence"))
cells.append(take("16", 29, "Exp 7"))
cells.append(take("16", 30, "DIRSPEC"))
cells.append(take("16", 31, "Save everything"))
cells.append(take("16", 32, "exp1_dark_binary"))

cells.append(md("""\
---
# Done — full retrain analysis complete

Fresh numbers for the paper: the 2×2 capture/gain (15), and all seven experiment tables in
`components_v1/` (16). Everything previously quoted was old-organism — replace it.
"""))
write_nb(ROOT / "meta_3_jspace.ipynb", cells)

print("OK")
